apiVersion: v1
kind: Service
metadata:
  name: svc-goodfood-postech-loadbalancer
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.0.10
  ports:
    - port: 8080
      nodePort: 32000
  selector:
    app: goodfood-postech